services:
  postgres:
    image: postgres:15-alpine
    container_name: eatzy_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eatzy_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d eatzy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: eatzy_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data